
default: &default
  adapter: mysql2
  username: root
  password:

development:
  <<: *default
  database: sky_service_dev

test:
  <<: *default
  database: sky_service_test

production:
  adapter: postgresql
  pool: 5
  encoding: unicode
  database: sky_service_prod
