
default: &default
  adapter: mysql2
  username: root
  password:

development:
  <<: *default
  database: sky_service_dev

test:
  <<: *default
  database: sky_service_test

production:
  <<: *default
  database: sky_service_prod
